### ISSUE TITLE
I always get: No such file or directory

### ISSUE THREAD

**Issue by GRboss** [entozoon/html-includes#1]
Hi,

No matter what I try I'm always getting the error: No such file or directory.

My node version is v8.4.0
My npm version is 5.3.0

Any idea how to overcome this?

Thanks

**Comment by entozoon** [comment]
Oh no, sorry to hear that!
What is your folder structure, and perhaps a code snippet?

Is it similar to the [use example](https://github.com/entozoon/html-includes#use) ?

**Comment by GRboss** [comment]
Here is an example:

```
$ mkdir source
$ echo 'hello' > source/index.html
$ mkdir target
$ ./node_modules/.bin/html-includes --src source/ --dest target/
```

Output:
```
: No such file or directory
```

**Comment by entozoon** [comment]
Yeah, that's not the intended way to use this module. Have you tried running it from a `package.json` script as in the [instructions](https://github.com/entozoon/html-includes#install)?

If you insist on running it from CLI, the reason your command doesn't work is because from the point of view of the script there is no source or target folder in that directory.

But fear not! You can try a few similar things - one of which is _sure_ to work (please let me know!):

```bash
./node_modules/.bin/html-includes --src ./source --dest ./target

./node_modules/.bin/html-includes --src ../../source --dest ../../target

node node_modules/html-includes/bin/compile.js --src ./source --dest ./target
```

**Comment by GRboss** [comment]
Well this is how it started. I was using it normally through the scripts section of the package.json file and I was getting the error. Anyway, I will try updating node and npm.

**Comment by entozoon** [comment]
Cool, let me know which works for you so I can update the README and close issue

**Comment by GRboss** [comment]
I tried with npm 5.5.2 and node 8.9.0 and it worked. Thanks
