### ISSUE TITLE
Feature Request: Option to turn off minification

### ISSUE THREAD

**Issue by iangilman** [entozoon/html-includes#10]
The minification is doing some bad things to my code at the moment, but even if it wasn't, I might want to leave the HTML unminified anyway just for easier readability (especially if I'm using html-includes for prototyping). Might be nice to have a flag to turn it off.

**Comment by entozoon** [comment]
You're absolutely right, thanks!

I've overhauled it with that hope that your issue is resolved with `v3.0.0` - minification is now off by default and you can add a `--minify` flag to enable it.

PS: Please update and also check the [readme](https://github.com/entozoon/html-includes/blob/master/README.md), as the usage is very slightly different

**Comment by iangilman** [comment]
Awesome! Thank you for the quick turn around!

**Comment by entozoon** [comment]
You're welcome. I'm just glad I've finally made something useful :)

**Comment by iangilman** [comment]
Yes, it's great! Nice to have something that solves this problem simply without having to use a whole framework :)
