### ISSUE TITLE
Feature Request: Src file pattern

### ISSUE THREAD

**Issue by philonor** [entozoon/html-includes#15]
**Problem**:
Having a project with many non-relevant sub-folders that contain html files, running `html-includes --src . --dest dist` results in compiling a lot of non-relevant sub-folder files.

**Possible Solution**:
Allow a file pattern like `./*.*` (following [glob](https://facelessuser.github.io/wcmatch/glob/) pattern).

**Comment by entozoon** [comment]
It does actually glob - see [this line](https://github.com/entozoon/html-includes/blob/master/bin/compile.js#L44)
```glob(args.src + "/**/*.html", {}, (err, files) => {```

So with your src of `.` it'll glob through `./**/*.html` bringing _any_ .html files through to your dist.

If, however, your files are prefixed with an underscore, i.e. `_foo.html`, then they won't get output. So that might be a way to stop it happening. Or just move your relevant files to a directory of their own.. keeping things nice and separate

**Comment by entozoon** [comment]
I have rewritten this package almost from scratch (😩!) and this issue should be resolved.

Please update to version `4.1.0` to try it, or see [HTML Includes Example](https://github.com/entozoon/html-includes-example) for a working test project.

If this bug still exists, pop a new issue report in and I'll see what I can do.
