### ISSUE TITLE
Feature Request: Adapt to allow HTML comment includes or attribute includes

### ISSUE THREAD

**Issue by philonor** [entozoon/html-includes#16]
In order to even increase helpfulness of this plugin, additionally allow html-comment includes.

**Problem**:
When developing e.g. with IntelliJ's live edit, you don't want another watch process.
Currently, we use [JS-includes](https://www.w3schools.com/howto/howto_html_include.asp) in the development environment for header, footer etc. 
We want to use your solution to insert includes for production in order to not require client-side scripting. 
Currently, in dev env, we have `${require('./inc/meta.html')` artifacts.

**Possible Solution**:
Allow requiring via comments, e.g. `<!--${require('./inc/meta.html')}-->`: Both solutions would work like this.

**Possible Solution 2**:
Preferably  allow requiring via attributes, e.g. `<div html-include=".inc/header.html"></div>`. This would allow `<div w3-include-html="./inc/header.html" html-include="./inc/header.html"></div>` and would work for both JS-includes (dev env) and html-includes (compilation of prod build).
If you allow to variably pick html attribute name via cmd line option, even better. E.g. having includes like `<div w3-include-html="./inc/header.html"></div>` and invocation `html-includes --src . --dest dist --attr-includes "w3-include-html"`.

Thanks for your work, if I find the time I might do some hands-on myself.

**Comment by entozoon** [comment]
Ah, I can understand your dilemma. Interestingly, I originally built it with an element style as you suggested.. along the lines of `<div include="_foo.html"></div>`
https://github.com/entozoon/html-includes/commit/127bb943d5d83c274a73faee4af670e293ed34b2

You're welcome to attempt to use that version, although I moved away from that markup style because the regex parsing was brutal and problematic so I wouldn't recommend it.

I'd suggest forking it to develop your custom solution.
More realistically however, you might want to think about upgrading to a more comprehensive bundler like webpack to work in your distinct environments
